[site]
name = "toke"
url = "https://tokelang.dev"
language = "en"

[build]
output = "build/"
minify = true
inlinecss = false

[server]
port = 8081
admin = false
workers = 0

[store]
backend = "flat"

[log]
accessformat = "combined"
maxlines = 10000
maxagedays = 30
