#!/usr/bin/env python3
"""
gen_roadmap.py -- generate the /roadmap page and the home-page milestones block
from ONE source file, so the two pages cannot disagree (story 132.9).

Source:   content/roadmap.json
Targets:  templates/roadmap.tkt                    (whole file, generated)
          templates/index.tkt  ROADMAP:BEGIN/END   (region, generated)

Usage:
    python3 scripts/gen_roadmap.py            # write both targets
    python3 scripts/gen_roadmap.py --check    # exit 1 if either target is stale

Every number in content/roadmap.json comes from ~/tk/toke/docs/metrics-baseline.md
and carries its tokenizer (or "bytes") and its N. This script computes nothing.
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "content" / "roadmap.json"
ROADMAP_TPL = ROOT / "templates" / "roadmap.tkt"
INDEX_TPL = ROOT / "templates" / "index.tkt"

BEGIN = "<!-- ROADMAP:BEGIN generated by scripts/gen_roadmap.py from content/roadmap.json -- do not edit by hand -->"
END = "<!-- ROADMAP:END -->"

STATUS_LABEL = {
    "done": "Done",
    "running": "Running now",
    "gated": "Compute-gated",
    "planned": "Planned",
}
STATUS_CLASS = {
    "done": "rm-done",
    "running": "rm-running",
    "gated": "rm-gated",
    "planned": "rm-planned",
}


# --------------------------------------------------------------------------
# /roadmap -- the full page
# --------------------------------------------------------------------------

STYLE = """<style>
/* Roadmap page (generated -- see scripts/gen_roadmap.py) */
.rm { max-width: 900px; margin: 0 auto; padding: 2.5rem 2rem 4rem; }
.rm h1 { font-size: 2.2rem; font-weight: 700; letter-spacing: -0.03em; color: #f5efe2; margin-bottom: 0.4rem; }
.rm h1 span { color: #f0c04a; }
.rm .lede { color: #9a9082; font-size: 0.95rem; line-height: 1.6; margin-bottom: 1.5rem; }
.rm .claim { border-left: 2px solid #f0c04a; padding: 0.2rem 0 0.2rem 1.1rem; margin: 0 0 2.5rem; }
.rm .claim .one { color: #f5efe2; font-size: 1.05rem; font-weight: 600; line-height: 1.45; margin-bottom: 0.7rem; }
.rm .claim .para { color: #9a9082; font-size: 0.87rem; line-height: 1.6; margin: 0; }
.rm h2 { font-size: 1.35rem; color: #f5efe2; margin: 3rem 0 0.5rem; letter-spacing: -0.02em; }
.rm h2:first-of-type { margin-top: 2rem; }
.rm .sub { color: #9a9082; font-size: 0.88rem; line-height: 1.6; margin-bottom: 1.25rem; }
.rm code { background: #201a11; border: 1px solid #2a2317; border-radius: 3px; padding: 0.1em 0.35em; font-size: 0.85em; color: #f0c04a; }
.rm a { color: #f0c04a; }

.rm .stage { border: 1px solid #2a2317; border-left-width: 3px; border-radius: 8px; background: #14110b; padding: 1.25rem 1.4rem; margin-bottom: 1rem; }
.rm .stage.rm-done { border-left-color: #6fc2b2; }
.rm .stage.rm-running { border-left-color: #f0c04a; }
.rm .stage.rm-gated { border-left-color: #6b6356; }
.rm .stage.rm-planned { border-left-color: #6b6356; }
.rm .stage-head { display: flex; align-items: baseline; gap: 0.6rem; flex-wrap: wrap; margin-bottom: 0.5rem; }
.rm .stage-label { font-family: 'JetBrains Mono', monospace; font-size: 0.72rem; letter-spacing: 0.06em; text-transform: uppercase; color: #6b6356; }
.rm .badge { font-size: 0.68rem; letter-spacing: 0.05em; text-transform: uppercase; border-radius: 20px; padding: 0.15rem 0.6rem; font-weight: 700; }
.rm .rm-done .badge { background: #17322d; color: #6fc2b2; }
.rm .rm-running .badge { background: #2a2317; color: #f0c04a; }
.rm .rm-gated .badge, .rm .rm-planned .badge { background: #1f1a11; color: #9a9082; }
.rm .stage-date { font-size: 0.72rem; color: #6b6356; margin-left: auto; font-family: 'JetBrains Mono', monospace; }
.rm .stage h3 { font-size: 1.05rem; color: #f5efe2; margin: 0 0 0.5rem; }
.rm .stage p { color: #9a9082; font-size: 0.87rem; line-height: 1.6; margin: 0 0 0.7rem; }
.rm .stage ul { margin: 0 0 0.7rem; padding-left: 1.1rem; }
.rm .stage li { color: #9a9082; font-size: 0.85rem; line-height: 1.6; margin-bottom: 0.4rem; }
.rm .stage strong { color: #f5efe2; }
.rm .caveat { border-left: 2px solid #6b6356; padding-left: 0.8rem; font-size: 0.82rem; color: #6b6356; margin: 0; }
.rm .caveat strong { color: #9a9082; }

.rm .bench { border: 1px solid #2a2317; border-radius: 8px; background: #14110b; padding: 1.1rem 1.3rem; margin-bottom: 0.9rem; }
.rm .bench-head { display: flex; align-items: baseline; gap: 0.6rem; flex-wrap: wrap; margin-bottom: 0.45rem; }
.rm .bench-id { font-family: 'JetBrains Mono', monospace; font-size: 0.75rem; color: #f0c04a; }
.rm .bench-name { color: #f5efe2; font-weight: 600; font-size: 0.97rem; }
.rm .bench-applies { margin-left: auto; font-size: 0.7rem; color: #6b6356; text-transform: uppercase; letter-spacing: 0.05em; }
.rm .bench p { color: #9a9082; font-size: 0.85rem; line-height: 1.6; margin: 0 0 0.5rem; }
.rm .bench .k { color: #6b6356; text-transform: uppercase; font-size: 0.68rem; letter-spacing: 0.06em; }
.rm .bench .veto { border-left: 2px solid #f0c04a; padding-left: 0.8rem; color: #f5efe2; font-size: 0.86rem; margin: 0.6rem 0 0; }

.rm .cols { display: grid; grid-template-columns: 1fr 1fr; gap: 1rem; }
@media (max-width: 720px) { .rm .cols { grid-template-columns: 1fr; } }
.rm .col { border: 1px solid #2a2317; border-radius: 8px; background: #14110b; padding: 1.1rem 1.3rem; }
.rm .col h4 { font-size: 0.9rem; color: #f5efe2; margin: 0 0 0.6rem; }
.rm .col ul { margin: 0; padding-left: 1.1rem; }
.rm .col li { color: #9a9082; font-size: 0.84rem; line-height: 1.6; margin-bottom: 0.45rem; }

.rm table { width: 100%; border-collapse: collapse; font-size: 0.83rem; margin-bottom: 1rem; }
.rm th { text-align: left; color: #6b6356; font-weight: 600; font-size: 0.72rem; text-transform: uppercase; letter-spacing: 0.05em; border-bottom: 1px solid #2a2317; padding: 0.5rem 0.6rem; }
.rm td { color: #9a9082; border-bottom: 1px solid #201a11; padding: 0.55rem 0.6rem; vertical-align: top; line-height: 1.55; }
.rm td strong { color: #f5efe2; }
.rm .rule { border-left: 2px solid #f0c04a; padding-left: 1rem; color: #f5efe2; font-size: 0.88rem; line-height: 1.6; }
.rm .src { color: #6b6356; font-size: 0.78rem; margin-top: 3rem; border-top: 1px solid #2a2317; padding-top: 1rem; line-height: 1.6; }
</style>"""


def esc_none(text):
    """Content in roadmap.json is authored as trusted HTML fragments."""
    return text


def render_stage(st):
    cls = STATUS_CLASS[st["status"]]
    out = [f'  <div class="stage {cls}" id="{st["id"]}">']
    out.append('    <div class="stage-head">')
    out.append(f'      <span class="stage-label">{st["label"]}</span>')
    out.append(f'      <span class="badge">{STATUS_LABEL[st["status"]]}</span>')
    out.append(f'      <span class="stage-date">{st["date"]}</span>')
    out.append("    </div>")
    out.append(f'    <h3>{st["title"]}</h3>')
    out.append(f'    <p>{st["summary"]}</p>')
    if st.get("results"):
        out.append("    <ul>")
        for r in st["results"]:
            out.append(f"      <li>{r}</li>")
        out.append("    </ul>")
    if st.get("caveat"):
        out.append(f'    <p class="caveat"><strong>Caveat.</strong> {st["caveat"]}</p>')
    out.append("  </div>")
    return "\n".join(out)


def render_bench(b):
    out = ['  <div class="bench">']
    out.append('    <div class="bench-head">')
    out.append(f'      <span class="bench-id">{b["id"]}</span>')
    out.append(f'      <span class="bench-name">{b["name"]}</span>')
    out.append(f'      <span class="bench-applies">{b["applies_to"]}</span>')
    out.append("    </div>")
    out.append(f'    <p><span class="k">Measures</span><br>{b["measures"]}</p>')
    out.append(f'    <p><span class="k">Why it is the benchmark</span><br>{b["why"]}</p>')
    if b.get("veto"):
        out.append(f'    <p class="veto"><strong>The veto:</strong> {b["veto"]}</p>')
    out.append("  </div>")
    return "\n".join(out)


def render_roadmap_page(d):
    p = []
    p.append('{! layout("base") !}')
    p.append("{! block(\"title\") !}Roadmap — toke{! end !}")
    p.append('{! block("content") !}')
    p.append("")
    p.append("<!-- GENERATED FILE. Edit content/roadmap.json, then run: python3 scripts/gen_roadmap.py -->")
    p.append("")
    p.append(STYLE)
    p.append("")
    p.append('<div class="rm">')
    p.append("")
    p.append("<h1>Roadmap, timeline and <span>plan</span></h1>")
    p.append(f'<p class="lede">{d["intro"]}</p>')
    p.append("")
    p.append('<div class="claim">')
    p.append(f'  <p class="one">{d["claim"]["one_liner"]}</p>')
    p.append(f'  <p class="para">{d["claim"]["paragraph"]}</p>')
    p.append("</div>")
    p.append("")

    p.append("<h2>The gate sequence</h2>")
    p.append('<p class="sub">Each stage carries what it actually produced, with the lane attached to every number, and the caveat that limits it.</p>')
    p.append("")
    for st in d["stages"]:
        p.append(render_stage(st))
        p.append("")

    p.append("<h2>What each stage is measured against</h2>")
    p.append('<p class="sub">These are the benchmarks, not the aspirations. They are being built before the training compute is spent, so that a result cannot be graded against criteria chosen after the fact &mdash; and so that a shift off BPE tokens costs a column rather than a rewrite.</p>')
    p.append("")
    for b in d["benchmarks"]:
        p.append(render_bench(b))
        p.append("")

    h = d["hedge"]
    p.append(f'<h2>{h["heading"]}</h2>')
    p.append(f'<p class="sub">{h["lead"]}</p>')
    p.append('<div class="cols">')
    p.append('  <div class="col">')
    p.append("    <h4>What does not survive</h4>")
    p.append("    <ul>")
    for x in h["does_not_survive"]:
        p.append(f"      <li>{x}</li>")
    p.append("    </ul>")
    p.append("  </div>")
    p.append('  <div class="col">')
    p.append("    <h4>What survives, and is arguably strengthened</h4>")
    p.append("    <ul>")
    for x in h["survives"]:
        p.append(f"      <li>{x}</li>")
    p.append("    </ul>")
    p.append("  </div>")
    p.append("</div>")
    p.append(f'<p class="rule" style="margin-top:1rem;"><strong>What would change in that world:</strong> {h["what_changes"]}</p>')
    p.append("")

    w = d["withdrawn"]
    p.append(f'<h2>{w["heading"]}</h2>')
    p.append(f'<p class="sub">{w["lead"]}</p>')
    p.append("<table>")
    p.append("  <thead><tr><th>Withdrawn claim</th><th>Why it cannot be requalified</th><th>What replaced it</th></tr></thead>")
    p.append("  <tbody>")
    for r in w["rows"]:
        p.append(f'    <tr><td>{r["claim"]}</td><td>{r["why"]}</td><td>{r["replacement"]}</td></tr>')
    p.append("  </tbody>")
    p.append("</table>")
    p.append(f'<p class="rule">{w["rule"]}</p>')
    p.append("")

    f = d["falsification"]
    p.append(f'<h2>{f["heading"]}</h2>')
    p.append(f'<p class="sub">{f["lead"]}</p>')
    p.append("<table>")
    p.append("  <thead><tr><th>Test</th><th>Result that falsifies it</th><th>Consequence</th></tr></thead>")
    p.append("  <tbody>")
    for r in f["rows"]:
        p.append(f'    <tr><td><strong>{r["test"]}</strong><br><span style="font-family:\'JetBrains Mono\',monospace;font-size:0.9em;color:#6b6356;">{r["id"]}</span></td><td>{r["falsifies"]}</td><td>{r["consequence"]}</td></tr>')
    p.append("  </tbody>")
    p.append("</table>")
    p.append("")

    nm = d["not_measured"]
    p.append(f'<h2>{nm["heading"]}</h2>')
    p.append("<ul>")
    for x in nm["items"]:
        p.append(f'  <li style="color:#9a9082;font-size:0.87rem;line-height:1.6;margin-bottom:0.5rem;">{x}</li>')
    p.append("</ul>")
    p.append("")

    p.append(
        '<p class="src">Every figure on this page is sourced from <code>%s</code> in the toke repository, '
        "which is the single reference for quantitative claims about toke and carries the methodology and caveat for each one. "
        "This page and the milestones block on the <a href=\"/\">home page</a> are generated from one file "
        "(<code>content/roadmap.json</code>) so that they cannot disagree. Last updated %s.</p>"
        % (d["source_of_numbers"], d["updated"])
    )
    p.append("")
    p.append("</div>")
    p.append("")
    p.append("{! end !}")
    p.append("")
    return "\n".join(p)


# --------------------------------------------------------------------------
# home page -- the compact milestones block
# --------------------------------------------------------------------------

INDEX_STYLE = """<style>
/* Milestones block (generated -- see scripts/gen_roadmap.py) */
.ms { max-width: 900px; margin: 0 auto 2rem; padding: 0 2rem; }
.ms-row { display: flex; gap: 1rem; padding: 0.9rem 0; border-bottom: 1px solid #201a11; align-items: baseline; }
.ms-row:last-child { border-bottom: none; }
.ms-key { flex: 0 0 8.5rem; }
.ms-label { display: block; font-family: 'JetBrains Mono', monospace; font-size: 0.72rem; letter-spacing: 0.06em; text-transform: uppercase; color: #f5efe2; }
.ms-status { display: inline-block; margin-top: 0.25rem; font-size: 0.64rem; letter-spacing: 0.05em; text-transform: uppercase; border-radius: 20px; padding: 0.12rem 0.55rem; font-weight: 700; }
.ms-done .ms-status { background: #17322d; color: #6fc2b2; }
.ms-running .ms-status { background: #2a2317; color: #f0c04a; }
.ms-gated .ms-status, .ms-planned .ms-status { background: #1f1a11; color: #9a9082; }
.ms-body { color: #9a9082; font-size: 0.87rem; line-height: 1.55; }
.ms-body strong { color: #f5efe2; }
.ms-body code { background: #201a11; border: 1px solid #2a2317; border-radius: 3px; padding: 0.1em 0.35em; font-size: 0.85em; color: #f0c04a; }
.ms-date { color: #6b6356; font-size: 0.75rem; font-family: 'JetBrains Mono', monospace; }
.ms-bench { margin-top: 1.5rem; border: 1px solid #2a2317; border-radius: 8px; background: #14110b; padding: 1.1rem 1.3rem; }
.ms-bench h4 { font-size: 0.9rem; color: #f5efe2; margin: 0 0 0.6rem; }
.ms-bench p { color: #9a9082; font-size: 0.85rem; line-height: 1.6; margin: 0 0 0.6rem; }
.ms-bench .veto { border-left: 2px solid #f0c04a; padding-left: 0.8rem; color: #f5efe2; margin: 0; }
.ms-cta { text-align: center; margin-top: 1.5rem; }
</style>"""


def render_index_block(d):
    p = [BEGIN]
    p.append("")
    p.append('<div class="section-heading">')
    p.append("  <h2>Where the project actually is</h2>")
    p.append("</div>")
    p.append(INDEX_STYLE)
    p.append('<div class="ms">')
    for st in d["stages"]:
        cls = "ms-" + st["status"].replace("gated", "gated")
        p.append(f'  <div class="ms-row {cls}">')
        p.append('    <div class="ms-key">')
        p.append(f'      <span class="ms-label">{st["label"]}</span>')
        p.append(f'      <span class="ms-status">{STATUS_LABEL[st["status"]]}</span><br>')
        p.append(f'      <span class="ms-date">{st["date"]}</span>')
        p.append("    </div>")
        p.append(f'    <div class="ms-body">{st["index_line"]}</div>')
        p.append("  </div>")
    p.append("</div>")

    scorecard = next(b for b in d["benchmarks"] if b.get("veto"))
    bench_ids = ", ".join(b["id"] for b in d["benchmarks"])
    p.append('<div class="ms" style="padding-top:0;">')
    p.append('  <div class="ms-bench">')
    p.append("    <h4>What each stage is measured against</h4>")
    p.append(
        '    <p>Six benchmarks (%s) cover multi-lane token counting, byte-level durability, '
        "constrained-decoding mask cost, cost per solved task, agentic token decomposition, and one "
        "pre-registered scorecard applied at every stage. They are being built before the training "
        "compute is spent.</p>" % bench_ids
    )
    p.append(f'    <p class="veto"><strong>The veto:</strong> {scorecard["veto"]}</p>')
    p.append("  </div>")
    p.append('  <div class="ms-cta">')
    p.append(
        '    <a href="/roadmap" style="background:#2a2317;border:1px solid #f0c04a;color:#f0c04a;'
        'padding:0.6rem 1.2rem;border-radius:6px;text-decoration:none;font-size:0.85rem;font-weight:600;">'
        "Full roadmap, benchmarks and withdrawn claims &rarr;</a>"
    )
    p.append("  </div>")
    p.append("</div>")
    p.append("")
    p.append(END)
    return "\n".join(p)


# --------------------------------------------------------------------------

def splice(text, block):
    if BEGIN not in text or END not in text:
        raise SystemExit(
            "templates/index.tkt has no ROADMAP:BEGIN/ROADMAP:END markers -- "
            "add them around the milestones block first."
        )
    head = text[: text.index(BEGIN)]
    tail = text[text.index(END) + len(END):]
    return head + block + tail


def main():
    check = "--check" in sys.argv
    d = json.loads(SRC.read_text(encoding="utf-8"))

    page = render_roadmap_page(d)
    index_text = INDEX_TPL.read_text(encoding="utf-8")
    new_index = splice(index_text, render_index_block(d))

    stale = []
    if not ROADMAP_TPL.exists() or ROADMAP_TPL.read_text(encoding="utf-8") != page:
        stale.append(str(ROADMAP_TPL.relative_to(ROOT)))
    if index_text != new_index:
        stale.append(str(INDEX_TPL.relative_to(ROOT)))

    if check:
        if stale:
            print("STALE (run: python3 scripts/gen_roadmap.py):")
            for s in stale:
                print("  " + s)
            return 1
        print("roadmap: templates/roadmap.tkt and templates/index.tkt are in sync with content/roadmap.json")
        return 0

    ROADMAP_TPL.write_text(page, encoding="utf-8")
    INDEX_TPL.write_text(new_index, encoding="utf-8")
    print("wrote templates/roadmap.tkt (%d stages, %d benchmarks)" % (len(d["stages"]), len(d["benchmarks"])))
    print("wrote templates/index.tkt ROADMAP:BEGIN/END block")
    return 0


if __name__ == "__main__":
    sys.exit(main())
